@echo off
echo Starting Client (Vite)...
start npm run dev
echo.
echo Starting Backend (Cloudflare Pages)...
echo Please wait for Vite to start first...
timeout /t 5
npx wrangler pages dev --proxy 5173
